package config

// RawLinks содержит прямые ссылки на текстовые файлы с периодически обновляемые списками TG-прокси из различных источников
var RawLinks = `
https://raw.githubusercontent.com/SoliSpirit/mtproto/refs/heads/master/all_proxies.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/xsfilternet/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/xsfilternet/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/xsfilternet/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/King_network7/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/King_network7/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/oneclickvpnkeys/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/oneclickvpnkeys/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/oneclickvpnkeys/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/V2rayEnglish/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/V2rayEnglish/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/V2rayEnglish/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/freenet_vt/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/freenet_vt/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/freenet_vt/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Proxy_Qavi/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Proxy_Qavi/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Proxy_Qavi/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/filembad/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/filembad/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/filembad/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/configfa/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/configfa/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/configfa/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/famoushaji/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/famoushaji/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/famoushaji/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/vasl_bashim/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/vasl_bashim/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/vasl_bashim/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/tel_melli/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/tel_melli/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/tel_melli/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/configraygan/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/configraygan/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/configraygan/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Father_vpn/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Father_vpn/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Father_vpn/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/tikvpnir/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/tikvpnir/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/tikvpnir/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/DarcProxy/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/DarcProxy/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/DarcProxy/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ShadowSocks_s/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ShadowSocks_s/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ShadowSocks_s/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/persianvpnhub/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/persianvpnhub/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/persianvpnhub/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/v2FreeHub/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/v2FreeHub/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/v2FreeHub/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/antimeli/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/antimeli/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/antimeli/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/An0nymousTeam/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/An0nymousTeam/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/An0nymousTeam/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/theAnixy/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/theAnixy/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/theAnixy/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/vpnRaya/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/vpnRaya/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/vpnRaya/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/proxy_kafee/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/proxy_kafee/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/proxy_kafee/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/iRoProxy/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/iRoProxy/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/iRoProxy/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/free_netplus/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/free_netplus/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/free_netplus/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Myporoxy/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Myporoxy/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/airdrop2033/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/airdrop2033/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/airdrop2033/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/SPEEDS_VPN1/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/SPEEDS_VPN1/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Capoit/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Capoit/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Capoit/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/i10VPN/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/i10VPN/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/i10VPN/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/aristapnel/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/aristapnel/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/aristapnel/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Speeds_vpn1/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Speeds_vpn1/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Speeds_vpn1/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/MARAMBASHI/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/MARAMBASHI/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/MARAMBASHI/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/wiki_tajrobe/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/wiki_tajrobe/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/wiki_tajrobe/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ProxySkull/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ProxySkull/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ProxySkull/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/NetAccount/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/NetAccount/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/NetAccount/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/PewezaVPN/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/PewezaVPN/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/PewezaVPN/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/FG_Link/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/FG_Link/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/FG_Link/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Hiddify_Nexttt/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Hiddify_Nexttt/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Hiddify_Nexttt/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/irancpi_vpn/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/irancpi_vpn/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/irancpi_vpn/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Proxy_Cloudy/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Proxy_Cloudy/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Proxy_Cloudy/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Express_freevpn/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Express_freevpn/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Express_freevpn/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/YeBeKhe/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/YeBeKhe/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/YeBeKhe/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/AKLISvpn/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/AKLISvpn/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/AKLISvpn/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/proxygodratmand/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/proxygodratmand/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Masyakata/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Masyakata/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Masyakata/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/meliproxyy/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/meliproxyy/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/meliproxyy/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/V2Ray_Tz/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/V2Ray_Tz/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/V2Ray_Tz/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/merlinvpn/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/merlinvpn/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/merlinvpn/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/saministamm/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/saministamm/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/saministamm/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Canfing_VPN/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Canfing_VPN/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Canfing_VPN/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/beshkan/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/beshkan/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/beshkan/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/AR14N24B/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/AR14N24B/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/AR14N24B/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/hacknashidd/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/hacknashidd/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/hacknashidd/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/neo_proxy/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/neo_proxy/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/neo_proxy/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/anty_filter/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/anty_filter/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/anty_filter/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/iphone02016vpn/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/iphone02016vpn/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/iphone02016vpn/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/KIA_NET/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/KIA_NET/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/KIA_NET/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ConfigWireguard/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ConfigWireguard/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ConfigWireguard/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/darkproxy/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/darkproxy/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/darkproxy/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/lrnbymaa/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/lrnbymaa/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/lrnbymaa/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/all/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/all/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/all/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/MatinSenPaii/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/MatinSenPaii/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/MatinSenPaii/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/IranProxyPlus/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/IranProxyPlus/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/IranProxyPlus/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Vpn_Sky/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Vpn_Sky/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/Vpn_Sky/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/hamedvpns/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/hamedvpns/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/hamedvpns/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/V2ray_official/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/V2ray_official/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/V2ray_official/tg_windows.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ProxyDaemi/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/ProxyDaemi/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/cooonfig/tg.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/cooonfig/tg_android.txt
https://raw.githubusercontent.com/10ium/VpnClashFaCollector/main/sub/cooonfig/tg_windows.txt
https://raw.githubusercontent.com/Firmfox/Proxify/refs/heads/main/telegram_proxies/mtproto.txt
https://raw.githubusercontent.com/Kolandone/v2raycollector/4486195aa2b4d89be970daeab05da6552cb4d6a6/proxy.txt
https://raw.githubusercontent.com/SoliSpirit/mtproto/master/all_proxies.txt
https://raw.githubusercontent.com/Grim1313/mtproto-for-telegram/refs/heads/master/all_proxies.txt
https://raw.githubusercontent.com/ALIILAPRO/MTProtoProxy/main/mtproto.txt
https://raw.githubusercontent.com/yemixzy/proxy-projects/main/proxies/mtproto.txt
https://raw.githubusercontent.com/kort0881/telegram-proxy-collector/refs/heads/main/proxy_all.txt
https://raw.githubusercontent.com/whoahaow/rjsxrd/refs/heads/main/githubmirror/tg-proxy/MTProto.txt
https://raw.githubusercontent.com/FLAT447/v2ray-lists/refs/heads/main/whitelist.txt
https://raw.githubusercontent.com/FLAT447/v2ray-lists/refs/heads/main/blacklist.txt
https://raw.githubusercontent.com/DepMSK37/proxy-list/refs/heads/main/verified/proxy_all_verified.txt
https://raw.githubusercontent.com/kort0881/telegram-proxy-collector/refs/heads/main/verified/proxy_all_tme_verified.txt
`
